version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "org.mvnpm:react-bootstrap"
  groups:
    quarkus:
      patterns:
        - "io.quarkus*"
        - "quarkus*"
    quarkiverse:
      patterns:
        - "io.quarkiverse*"
    mvnpm:
      patterns:
        - "org.mvnpm*"
    dependencies:
      patterns:
        - "*"
      exclude-patterns:
        - "io.quarkus*"
        - "quarkus*"
        - "org.mvnpm*"
        - "io.quarkiverse*"
