version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    quarkus:
      patterns:
        - "io.quarkus*"
        - "quarkus*"
    dependencies:
      patterns:
        - "*"
      exclude-patterns:
        - "io.quarkus*"
        - "quarkus*"
        - "io.mvnpm*"
    mvnpm:
      patterns:
        - "io.mvnpm*"
      exclude-patterns:
        - "io.mvnpm:react-bootstrap"
