trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean package'
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.11'
    options: ''