version: "3.9"
services:
  code-quarkus-api:
    image: quay.io/quarkus/code-quarkus-api
    ports:
      - "8080:8080"
  code-quarkus-frontend:
    image: quay.io/quarkus/code-quarkus-frontend
    ports:
      - "3000:8082"
    depends_on:
      - code-quarkus-api
