version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/repo/src/main/frontend/yarn.lock" }}

      - run:
          name: Prepare dependencies
          command: mvn dependency:go-offline && mvn frontend:install-node-and-yarn &&  mvn frontend:yarn@"yarn install"

      - save_cache:
          paths:
            - ~/.m2
            - ~/repo/node
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/repo/src/main/frontend/yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: mvn package

      # Store context
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - repo

workflows:
  version: 2
  ci:
    jobs:
      - build