version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/library"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/acceptance-test"
    schedule:
      interval: "daily"