---
apiVersion: v1
kind: Template
metadata:
  name: code-quarkus-frontend-acceptance-test
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: code-quarkus-frontend-acceptance-test-${IMAGE_TAG}
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: quay.io/quarkus/code-quarkus-acceptance-test:latest
              imagePullPolicy: Always
              name: code-quarkus-acceptance-test
              env:
                - name: TEST_CONFIG_URL
                  value: ${CODE_QUARKUS_STAGING_URL}
parameters:
  - name: IMAGE
    value: ''
  - name: IMAGE_TAG
    value: ''
    required: true
  - name: CODE_QUARKUS_STAGING_URL
    value: 'https://stage.code.quarkus.io'
    optional: true
