---
apiVersion: v1
kind: Template
metadata:
  name: code-quarkus
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: code-quarkus
    spec:
      replicas: ${{REPLICAS}}
      selector:
        service: code-quarkus
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            service: code-quarkus
        spec:
          containers:
            - image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: code-quarkus-app
              ports:
                - containerPort: 8080
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 8080
                initialDelaySeconds: 3
                periodSeconds: 10
                timeoutSeconds: 3
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
              env:
                - name: SENTRY_DSN
                  value: ${CODE_QUARKUS_SENTRY_DSN}
                - name: ENV
                  value: ${CODE_QUARKUS_ENV}
                - name: GA_TRACKING_ID
                  value: ${CODE_QUARKUS_GA_TRACKING_ID}
      triggers:
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        service: code-quarkus
      name: code-quarkus
    spec:
      ports:
        - name: '8080'
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        service: code-quarkus
      sessionAffinity: None
      type: ClusterIP
parameters:
  - name: CODE_QUARKUS_SENTRY_DSN
    displayName: Code Quarkus App sentry dsn
    description: Code Quarkus App sentry dsn.
  - name: CODE_QUARKUS_ENV
    value: dev
    required: true
    displayName: Code Quarkus App environment
    description: Code Quarkus App environment. Defaults to dev
  - name: CODE_QUARKUS_GA_TRACKING_ID
    displayName: Code Quarkus App ga tracking id
    description: Code Quarkus App google analytics tracking id.
  - name: IMAGE
    value: quay.io/quarkus/code-quarkus-app
    required: true
    displayName: Code Quarkus App image
    description: Code Quarkus App docker image. Defaults to quay.io/quarkus/code-quarkus-app
  - name: IMAGE_TAG
    value: latest
    required: true
    displayName: Code Quarkus App version
    description: Code Quarkus App version which defaults to latest
  - name: MEMORY_LIMIT
    value: 1Gi
    required: true
    displayName: Memory Limit
    description: Maximum amount of memory the container can use. Defaults 1Gi
  - description: Number of deployment replicas
    displayName: Number of deployment replicas
    required: true
    name: REPLICAS
    value: '1'