---
apiVersion: v1
kind: Template
metadata:
  name: launcher-quarkus
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: launcher-quarkus
    spec:
      replicas: ${REPLICAS}
      selector:
        service: launcher-quarkus
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            service: launcher-quarkus
        spec:
          containers:
            - image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: launcher-quarkus
              ports:
                - containerPort: 8080
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 8080
                initialDelaySeconds: 3
                periodSeconds: 10
                timeoutSeconds: 3
              resources:
                limits:
                  memory: ${MEMORY_LIMIT}
              env:
                - name: LAUNCHER_QUARKUS_SENTRY_DSN
                  value: ${LAUNCHER_QUARKUS_SENTRY_DSN}
                - name: LAUNCHER_QUARKUS_ENV
                  value: ${LAUNCHER_QUARKUS_ENV}
                - name: LAUNCHER_QUARKUS_GA_TRACKING_ID
                  value: ${LAUNCHER_QUARKUS_GA_TRACKING_ID}
      triggers:
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        service: launcher-quarkus
      name: launcher-quarkus
    spec:
      ports:
        - name: '8080'
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        service: launcher-quarkus
      sessionAffinity: None
      type: ClusterIP
parameters:
  - name: LAUNCHER_QUARKUS_SENTRY_DSN
    displayName: launcher quarkus sentry dsn
    description: launcher quarkus sentry dsn.
  - name: LAUNCHER_QUARKUS_ENV
    value: dev
    required: true
    displayName: launcher quarkus environment
    description: launcher quarkus environment. Defaults to dev
  - name: LAUNCHER_QUARKUS_GA_TRACKING_ID
    displayName: launcher quarkus ga tracking id
    description: launcher quarkus google analytics tracking id.
  - name: IMAGE
    value: quay.io/launcher/launcher-quarkus
    required: true
    displayName: launcher quarkus image
    description: launcher quarkus docker image. Defaults to quay.io/launcher/launcher-quarkus
  - name: IMAGE_TAG
    value: latest
    required: true
    displayName: launcher quarkus version
    description: launcher quarkus version which defaults to latest
  - name: MEMORY_LIMIT
    value: 1Gi
    required: true
    displayName: Memory Limit
    description: Maximum amount of memory the container can use. Defaults 1Gi
  - description: Number of deployment replicas
    displayName: Number of deployment replicas
    required: true
    name: REPLICAS
    value: '1'