---
apiVersion: v1
kind: Template
metadata:
  name: code-quarkus
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: code-quarkus
    spec:
      replicas: ${{REPLICAS}}
      selector:
        service: code-quarkus
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            service: code-quarkus
        spec:
          containers:
            - image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: code-quarkus-app
              ports:
                - containerPort: 8080
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 10
                timeoutSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 10
                timeoutSeconds: 3
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              env:
                - name: IO_QUARKUS_CODE_ENVIRONMENT
                  value: ${IO_QUARKUS_CODE_ENVIRONMENT}
                - name: IO_QUARKUS_CODE_GA_EXTENSIONS_DIMENSION_INDEX
                  value: ${IO_QUARKUS_CODE_GA_EXTENSIONS_DIMENSION_INDEX}
                - name: IO_QUARKUS_CODE_GA_QUARKUS_VERSION_DIMENSION_INDEX
                  value: ${IO_QUARKUS_CODE_GA_QUARKUS_VERSION_DIMENSION_INDEX}
                - name: IO_QUARKUS_CODE_GA_BUILD_TOOL_DIMENSION_INDEX
                  value: ${IO_QUARKUS_CODE_GA_BUILD_TOOL_DIMENSION_INDEX}
                - name: IO_QUARKUS_CODE_GA_EXTENSION_QUANTITY_INDEX
                  value: ${IO_QUARKUS_CODE_GA_EXTENSION_QUANTITY_INDEX}
                - name: IO_QUARKUS_CODE_GA_BATCHING_ENABLED
                  value: ${IO_QUARKUS_CODE_GA_BATCHING_ENABLED}
                - name: IO_QUARKUS_CODE_LOG_LEVEL
                  value: ${IO_QUARKUS_CODE_LOG_LEVEL}
                - name: IO_QUARKUS_CODE_HOSTNAME
                  value: ${IO_QUARKUS_CODE_HOSTNAME}
                - name: IO_QUARKUS_CODE_FEATURES
                  value: ${IO_QUARKUS_CODE_FEATURES}
                - name: IO_QUARKUS_CODE_SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: sentry-dsn
                - name: QUARKUS_LOG_SENTRY
                  value: "true"
                - name: QUARKUS_LOG_SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: sentry-dsn
                - name: IO_QUARKUS_CODE_GA_TRACKING_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: ga-tracking-id
      triggers:
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        service: code-quarkus
      name: code-quarkus
    spec:
      ports:
        - name: '8080'
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        service: code-quarkus
      sessionAffinity: None
      type: ClusterIP
parameters:
  - name: IO_QUARKUS_CODE_ENVIRONMENT
    value: dev
    required: true
    displayName: Code Quarkus App environment
    description: Code Quarkus App environment. Defaults to dev
  - name: IO_QUARKUS_CODE_FEATURES
    displayName: Features
    description: Code Quarkus App enabled features
  - name: IO_QUARKUS_CODE_HOSTNAME
    required: true
    displayName: Code Quarkus Hostname
    description: Code Quarkus Hostname
  - name: IO_QUARKUS_CODE_GA_BATCHING_ENABLED
    value: "true"
    required: true
    displayName: Code Quarkus Google Analytics enabled batching
    description: Code Quarkus Google Analytics enabled batching
  - name: IO_QUARKUS_CODE_LOG_LEVEL
    value: "INFO"
    required: true
    displayName: Code Quarkus log level
    description: Code Quarkus log level
  - name: IO_QUARKUS_CODE_GA_EXTENSIONS_DIMENSION_INDEX
    required: false
    displayName: Code Quarkus Google Analytics extensions dimension index
    description: Code Quarkus Google Analytics extensions dimension index
  - name: IO_QUARKUS_CODE_GA_QUARKUS_VERSION_DIMENSION_INDEX
    required: false
    displayName: Code Quarkus Google Analytics Quarkus version dimension index
    description: Code Quarkus Google Analytics Quarkus version dimension index
  - name: IO_QUARKUS_CODE_GA_BUILD_TOOL_DIMENSION_INDEX
    required: false
    displayName: Code Quarkus Google Analytics build tool dimension index
    description: Code Quarkus Google Analytics build tool dimension index
  - name: IO_QUARKUS_CODE_GA_EXTENSION_QUANTITY_INDEX
    required: false
    displayName: Code Quarkus Google Analytics extension qty dimension index
    description: Code Quarkus Google Analytics extension qty dimension index
  - name: IMAGE
    value: quay.io/quarkus/code-quarkus-app
    required: true
    displayName: Code Quarkus App image
    description: Code Quarkus App docker image. Defaults to quay.io/quarkus/code-quarkus-app
  - name: IMAGE_TAG
    value: latest
    required: true
    displayName: Code Quarkus App version
    description: Code Quarkus App version which defaults to latest
  - description: CPU request
    displayName: CPU request
    required: true
    name: CPU_REQUEST
    value: 400m
  - description: CPU limit
    displayName: CPU limit
    required: true
    name: CPU_LIMIT
    value: 1000m
  - description: Memory request
    displayName: Memory request
    required: true
    name: MEMORY_REQUEST
    value: 768Mi
  - description: Memory limit
    displayName: Memory limit
    required: true
    name: MEMORY_LIMIT
    value: 1Gi
  - description: Number of deployment replicas
    displayName: Number of deployment replicas
    required: true
    name: REPLICAS
    value: '1'