name: Acceptance Test Tests
on:
  push:
    paths:
      - 'pom.xml'
      - 'api/**'
      - '.github/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review, edited]
    paths:
      - 'pom.xml'
      - 'acceptance-test/**'
      - '.github/**'

env:
  # Workaround testsuite locale issue
  LANG: en_US.UTF-8

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: openjdk17
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('acceptance-test/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        working-directory: acceptance-test
        run: |
          mvn -e -B -DskipTests=true clean package
      - name: Test
        working-directory: acceptance-test
        run: |
          mvn -e -B verify
