name: Code Quarkus Frontend CI
on:
  push:
    paths:
      - 'frontend/**'
      - 'library/**'
      - '.github/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review, edited]
    paths:
      - 'frontend/**'
      - 'library/**'
      - '.github/**'

env:
  # Workaround testsuite locale issue
  LANG: en_US.UTF-8

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
          path: ~/.bvm
          key: ${{ runner.os }}-bvm-bit
          restore-keys: |
            ${{ runner.os }}-bvm-bit
      - name: Install library packages
        working-directory: library
        run: npm ci
      - name: Build Library
        working-directory: library
        run: npm run build
      - name: Link Library
        working-directory: frontend
        run: npm run link-library
      - name: Install frontend
        working-directory: frontend
        run: npm ci
      - name: Build frontend
        working-directory: frontend
        run: npm run build
